pipeline:
  tests:
    image: centos:${OS_VERSION}
    pull: true
    commands:
      - if test "$${FORCED_OS_VERSION}" != ""; then if test "$${FORCED_OS_VERSION}" != "${OS_VERSION}"; then echo "step bypass"; exit 0; fi; fi
      - echo -e "[metwork_${DRONE_BRANCH}]\nname=Metwork Continuous Integration Branch ${DRONE_BRANCH}\nbaseurl=http://metwork-framework.org/pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/centos7/\ngpgcheck=0\nenabled=1\nmetadata_expire=0\n" >/etc/yum.repos.d/metwork.repo
      - yum -y install metwork-mfext metwork-mfext-integration-tests

matrix:
  OS_VERSION:
    - centos6
    - centos7

branches: [ master, integration, ci_* ]
